name: PSPDNA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install PSPSDK dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        build-essential cmake pkgconf \
        libreadline8 libusb-0.1 libgpgme11 \
        libarchive-tools fakeroot wget

    - name: Download latest PSPSDK
      run: |
        wget https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest-x86_64.tar.gz
        mkdir -p "$HOME/pspdev" # Создаём целевой каталог
        tar -xvf pspdev-ubuntu-latest-x86_64.tar.gz -C "$HOME/pspdev" --strip-components=1

    - name: Add PSPSDK to PATH
      run: |
        echo "PSPDEV=$HOME/pspdev" >> $GITHUB_ENV
        echo "$HOME/pspdev/bin" >> $GITHUB_PATH

    - name: Install Mono
      run: |
        sudo apt-get update
        sudo apt install -y mono-devel

    - name: Run make rebuild
      run: make rebuild
