name: PSPDNA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install PSPSDK dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential cmake pkgconf libreadline8 libusb-0.1 libgpgme11 libarchive-tools fakeroot wget

    - name: Download latest PSPSDK
      run: |
        wget https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest-x86_64.tar.gz
        tar -xvf pspdev-ubuntu-latest-x86_64.tar.gz

    - name: Add PSPSDK to PATH
      run: |
        echo "/usr/local/pspdev/bin" >> $GITHUB_PATH

    - name: configure
      run: ./configure

